FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -o migrate ./cmd/migrate

FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /app/migrate /app/migrate

ENTRYPOINT ["/app/migrate"]
